/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 concerto.glb 
Author: Gregory Khodyrev (https://sketchfab.com/gmaaailgrisha)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/concerto-c8f9ff8fd8fd404b8432ba0982c40034
Title: Concerto
*/

// import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Concerto(props) {
  const { nodes, materials } = useGLTF('/models/concerto.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={1.466}>
        <group position={[0, 0, 0.625]} rotation={[0, 0, -0.635]}>
          <mesh geometry={nodes.Roundcube_0.geometry} material={materials.Head} />
          <mesh geometry={nodes.Roundcube_1.geometry} material={materials.Bill} />
          <mesh geometry={nodes.Roundcube_2.geometry} material={materials.material_3} />
          <mesh geometry={nodes.Roundcube_3.geometry} material={materials.pale_white} />
          <mesh geometry={nodes.Roundcube_4.geometry} material={materials.Bill2} />
        </group>
        <group position={[-1.5, -1.603, 0.456]} rotation={[-0.135, -0.252, -0.5]}>
          <mesh geometry={nodes.Frog_Body_0.geometry} material={materials.Head} />
          <mesh geometry={nodes.Frog_Body_1.geometry} material={materials.material_3} />
          <mesh geometry={nodes.Frog_Body_2.geometry} material={materials.Viola} />
          <mesh geometry={nodes.Frog_Body_3.geometry} material={materials.Frog} />
          <mesh geometry={nodes.Frog_Body_4.geometry} material={materials.Frog_2} />
          <mesh geometry={nodes.Frog_Body_5.geometry} material={materials.material} />
        </group>
        <group position={[-1.805, -0.409, -4.583]} rotation={[-Math.PI / 2, 1.433, Math.PI / 2]}>
          <mesh geometry={nodes.Circle007_0.geometry} material={materials.Leaf} />
          <mesh geometry={nodes.Circle007_0_1.geometry} material={materials.Leaf} />
        </group>
        <group position={[0, 0, -1.185]} rotation={[0, 0, -0.635]}>
          <mesh geometry={nodes.Roundcube001_0.geometry} material={materials.Head} />
          <mesh geometry={nodes.Roundcube001_1.geometry} material={materials.Bill} />
          <mesh geometry={nodes.Roundcube001_2.geometry} material={materials.material_3} />
          <mesh geometry={nodes.Roundcube001_3.geometry} material={materials.pale_white} />
          <mesh geometry={nodes.Roundcube001_4.geometry} material={materials.Bill2} />
        </group>
        <mesh geometry={nodes.Plane_0.geometry} material={materials.Water} />
        <mesh geometry={nodes.Plane001_0.geometry} material={materials.Water} position={[0, 0, -2.033]} rotation={[0, 0, -Math.PI]} />
        <mesh geometry={nodes.Vert_0.geometry} material={materials.material} position={[-1.621, -1.661, 0.632]} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/concerto.glb')
