/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 halloween.glb 
Author: LeafChan (https://sketchfab.com/CuteLeaf)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/halloween-2ec65917ad7f4568850260567172cf10
Title: Halloween!!🎃 👻 🍭
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Halloween(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('./models/halloween.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="9e40baac87524264a203ac3717fbd6e9fbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="group23">
                  <group name="polySurface53">
                    <mesh name="polySurface53_aiStandardSurface2_0" geometry={nodes.polySurface53_aiStandardSurface2_0.geometry} material={materials.aiStandardSurface2} />
                  </group>
                </group>
                <group name="group25">
                  <group name="group18">
                    <group name="pPlane16" position={[2.607, -1.796, -1.815]}>
                      <mesh name="pPlane16_aiStandardSurface4_0" geometry={nodes.pPlane16_aiStandardSurface4_0.geometry} material={materials.aiStandardSurface4} />
                    </group>
                    <group name="pPlane15" position={[3.216, -2.165, -1.972]}>
                      <mesh name="pPlane15_aiStandardSurface4_0" geometry={nodes.pPlane15_aiStandardSurface4_0.geometry} material={materials.aiStandardSurface4} />
                    </group>
                    <group name="pPlane11" position={[3.535, 1.297, -3.705]}>
                      <mesh name="pPlane11_aiStandardSurface4_0" geometry={nodes.pPlane11_aiStandardSurface4_0.geometry} material={materials.aiStandardSurface4} />
                    </group>
                    <group name="pPlane8" position={[-0.193, 2.585, -3.705]}>
                      <mesh name="pPlane8_aiStandardSurface4_0" geometry={nodes.pPlane8_aiStandardSurface4_0.geometry} material={materials.aiStandardSurface4} />
                    </group>
                    <group name="pPlane21" position={[-2.505, -2.516, -4.576]}>
                      <mesh name="pPlane21_aiStandardSurface4_0" geometry={nodes.pPlane21_aiStandardSurface4_0.geometry} material={materials.aiStandardSurface4} />
                    </group>
                    <group name="pPlane22" position={[-2.904, 2.023, -3.692]}>
                      <mesh name="pPlane22_aiStandardSurface4_0" geometry={nodes.pPlane22_aiStandardSurface4_0.geometry} material={materials.aiStandardSurface4} />
                    </group>
                    <group name="pPlane23" position={[-0.026, 1.452, -4.489]}>
                      <mesh name="pPlane23_aiStandardSurface4_0" geometry={nodes.pPlane23_aiStandardSurface4_0.geometry} material={materials.aiStandardSurface4} />
                    </group>
                    <group name="pPlane24" position={[3.477, -0.965, -4.141]}>
                      <mesh name="pPlane24_aiStandardSurface4_0" geometry={nodes.pPlane24_aiStandardSurface4_0.geometry} material={materials.aiStandardSurface4} />
                    </group>
                    <group name="pPlane25" position={[-4.501, -0.416, -3.705]}>
                      <mesh name="pPlane25_aiStandardSurface4_0" geometry={nodes.pPlane25_aiStandardSurface4_0.geometry} material={materials.aiStandardSurface4} />
                    </group>
                    <group name="pPlane26" position={[1.442, -1.408, -3.705]}>
                      <mesh name="pPlane26_aiStandardSurface4_0" geometry={nodes.pPlane26_aiStandardSurface4_0.geometry} material={materials.aiStandardSurface4} />
                    </group>
                    <group name="pPlane27" position={[4.557, -2.437, -3.705]}>
                      <mesh name="pPlane27_aiStandardSurface4_0" geometry={nodes.pPlane27_aiStandardSurface4_0.geometry} material={materials.aiStandardSurface4} />
                    </group>
                    <group name="pPlane34" position={[4.115, 0.709, -3.705]}>
                      <mesh name="pPlane34_aiStandardSurface4_0" geometry={nodes.pPlane34_aiStandardSurface4_0.geometry} material={materials.aiStandardSurface4} />
                    </group>
                    <group name="pPlane35" position={[-1.724, -2.173, -3.705]}>
                      <mesh name="pPlane35_aiStandardSurface4_0" geometry={nodes.pPlane35_aiStandardSurface4_0.geometry} material={materials.aiStandardSurface4} />
                    </group>
                    <group name="pPlane38" position={[3.03, -2.443, -1.972]}>
                      <mesh name="pPlane38_aiStandardSurface4_0" geometry={nodes.pPlane38_aiStandardSurface4_0.geometry} material={materials.aiStandardSurface4} />
                    </group>
                    <group name="pPlane6">
                      <mesh name="pPlane6_aiStandardSurface4_0" geometry={nodes.pPlane6_aiStandardSurface4_0.geometry} material={materials.aiStandardSurface4} />
                    </group>
                    <group name="pPlane7">
                      <mesh name="pPlane7_aiStandardSurface4_0" geometry={nodes.pPlane7_aiStandardSurface4_0.geometry} material={materials.aiStandardSurface4} />
                    </group>
                    <group name="pPlane2">
                      <mesh name="pPlane2_aiStandardSurface4_0" geometry={nodes.pPlane2_aiStandardSurface4_0.geometry} material={materials.aiStandardSurface4} />
                    </group>
                    <group name="pPlane1">
                      <mesh name="pPlane1_aiStandardSurface4_0" geometry={nodes.pPlane1_aiStandardSurface4_0.geometry} material={materials.aiStandardSurface4} />
                    </group>
                    <group name="pPlane20">
                      <mesh name="pPlane20_aiStandardSurface4_0" geometry={nodes.pPlane20_aiStandardSurface4_0.geometry} material={materials.aiStandardSurface4} />
                    </group>
                    <group name="pPlane5">
                      <mesh name="pPlane5_aiStandardSurface4_0" geometry={nodes.pPlane5_aiStandardSurface4_0.geometry} material={materials.aiStandardSurface4} />
                    </group>
                    <group name="pPlane3">
                      <mesh name="pPlane3_aiStandardSurface4_0" geometry={nodes.pPlane3_aiStandardSurface4_0.geometry} material={materials.aiStandardSurface4} />
                    </group>
                    <group name="pPlane4">
                      <mesh name="pPlane4_aiStandardSurface4_0" geometry={nodes.pPlane4_aiStandardSurface4_0.geometry} material={materials.aiStandardSurface4} />
                    </group>
                    <group name="pPlane18">
                      <mesh name="pPlane18_aiStandardSurface4_0" geometry={nodes.pPlane18_aiStandardSurface4_0.geometry} material={materials.aiStandardSurface4} />
                    </group>
                    <group name="pPlane19">
                      <mesh name="pPlane19_aiStandardSurface4_0" geometry={nodes.pPlane19_aiStandardSurface4_0.geometry} material={materials.aiStandardSurface4} />
                    </group>
                    <group name="pPlane17" position={[0, 0, -0.074]}>
                      <mesh name="pPlane17_aiStandardSurface4_0" geometry={nodes.pPlane17_aiStandardSurface4_0.geometry} material={materials.aiStandardSurface4} />
                    </group>
                    <group name="pPlane9">
                      <mesh name="pPlane9_aiStandardSurface4_0" geometry={nodes.pPlane9_aiStandardSurface4_0.geometry} material={materials.aiStandardSurface4} />
                    </group>
                    <group name="pPlane10">
                      <mesh name="pPlane10_aiStandardSurface4_0" geometry={nodes.pPlane10_aiStandardSurface4_0.geometry} material={materials.aiStandardSurface4} />
                    </group>
                    <group name="pPlane12">
                      <mesh name="pPlane12_aiStandardSurface4_0" geometry={nodes.pPlane12_aiStandardSurface4_0.geometry} material={materials.aiStandardSurface4} />
                    </group>
                    <group name="pPlane28">
                      <mesh name="pPlane28_aiStandardSurface4_0" geometry={nodes.pPlane28_aiStandardSurface4_0.geometry} material={materials.aiStandardSurface4} />
                    </group>
                    <group name="pPlane29">
                      <mesh name="pPlane29_aiStandardSurface4_0" geometry={nodes.pPlane29_aiStandardSurface4_0.geometry} material={materials.aiStandardSurface4} />
                    </group>
                    <group name="pPlane30">
                      <mesh name="pPlane30_aiStandardSurface4_0" geometry={nodes.pPlane30_aiStandardSurface4_0.geometry} material={materials.aiStandardSurface4} />
                    </group>
                    <group name="pPlane31">
                      <mesh name="pPlane31_aiStandardSurface4_0" geometry={nodes.pPlane31_aiStandardSurface4_0.geometry} material={materials.aiStandardSurface4} />
                    </group>
                    <group name="pPlane32">
                      <mesh name="pPlane32_aiStandardSurface4_0" geometry={nodes.pPlane32_aiStandardSurface4_0.geometry} material={materials.aiStandardSurface4} />
                    </group>
                    <group name="pPlane33">
                      <mesh name="pPlane33_aiStandardSurface4_0" geometry={nodes.pPlane33_aiStandardSurface4_0.geometry} material={materials.aiStandardSurface4} />
                    </group>
                    <group name="pPlane36">
                      <mesh name="pPlane36_aiStandardSurface4_0" geometry={nodes.pPlane36_aiStandardSurface4_0.geometry} material={materials.aiStandardSurface4} />
                    </group>
                    <group name="pPlane37">
                      <mesh name="pPlane37_aiStandardSurface4_0" geometry={nodes.pPlane37_aiStandardSurface4_0.geometry} material={materials.aiStandardSurface4} />
                    </group>
                    <group name="pPlane39">
                      <mesh name="pPlane39_aiStandardSurface4_0" geometry={nodes.pPlane39_aiStandardSurface4_0.geometry} material={materials.aiStandardSurface4} />
                    </group>
                    <group name="pPlane40" position={[-0.65, -1.199, -0.168]}>
                      <mesh name="pPlane40_aiStandardSurface4_0" geometry={nodes.pPlane40_aiStandardSurface4_0.geometry} material={materials.aiStandardSurface4} />
                    </group>
                    <group name="pPlane41" position={[0.643, -1.42, -0.994]} scale={0.557}>
                      <mesh name="pPlane41_aiStandardSurface4_0" geometry={nodes.pPlane41_aiStandardSurface4_0.geometry} material={materials.aiStandardSurface4} />
                    </group>
                  </group>
                </group>
                <group name="group28" scale={0.998}>
                  <group name="polySurface88">
                    <group name="polySurface118">
                      <mesh name="polySurface118_aiStandardSurface2_0" geometry={nodes.polySurface118_aiStandardSurface2_0.geometry} material={materials.aiStandardSurface2} />
                    </group>
                    <group name="polySurface119">
                      <mesh name="polySurface119_aiStandardSurface2_0" geometry={nodes.polySurface119_aiStandardSurface2_0.geometry} material={materials.aiStandardSurface2} />
                    </group>
                    <group name="polySurface120">
                      <mesh name="polySurface120_aiStandardSurface2_0" geometry={nodes.polySurface120_aiStandardSurface2_0.geometry} material={materials.aiStandardSurface2} />
                    </group>
                    <group name="polySurface121">
                      <mesh name="polySurface121_aiStandardSurface2_0" geometry={nodes.polySurface121_aiStandardSurface2_0.geometry} material={materials.aiStandardSurface2} />
                    </group>
                    <group name="polySurface122">
                      <mesh name="polySurface122_aiStandardSurface2_0" geometry={nodes.polySurface122_aiStandardSurface2_0.geometry} material={materials.aiStandardSurface2} />
                    </group>
                    <group name="polySurface123">
                      <mesh name="polySurface123_aiStandardSurface2_0" geometry={nodes.polySurface123_aiStandardSurface2_0.geometry} material={materials.aiStandardSurface2} />
                    </group>
                    <group name="polySurface124">
                      <mesh name="polySurface124_aiStandardSurface2_0" geometry={nodes.polySurface124_aiStandardSurface2_0.geometry} material={materials.aiStandardSurface2} />
                    </group>
                    <group name="polySurface125">
                      <mesh name="polySurface125_aiStandardSurface2_0" geometry={nodes.polySurface125_aiStandardSurface2_0.geometry} material={materials.aiStandardSurface2} />
                    </group>
                    <group name="polySurface126">
                      <mesh name="polySurface126_aiStandardSurface2_0" geometry={nodes.polySurface126_aiStandardSurface2_0.geometry} material={materials.aiStandardSurface2} />
                    </group>
                    <group name="polySurface127">
                      <mesh name="polySurface127_aiStandardSurface2_0" geometry={nodes.polySurface127_aiStandardSurface2_0.geometry} material={materials.aiStandardSurface2} />
                    </group>
                    <group name="polySurface128">
                      <mesh name="polySurface128_aiStandardSurface2_0" geometry={nodes.polySurface128_aiStandardSurface2_0.geometry} material={materials.aiStandardSurface2} />
                    </group>
                    <group name="polySurface129">
                      <mesh name="polySurface129_aiStandardSurface2_0" geometry={nodes.polySurface129_aiStandardSurface2_0.geometry} material={materials.aiStandardSurface2} />
                    </group>
                    <group name="polySurface130">
                      <mesh name="polySurface130_aiStandardSurface2_0" geometry={nodes.polySurface130_aiStandardSurface2_0.geometry} material={materials.aiStandardSurface2} />
                    </group>
                    <group name="polySurface131">
                      <mesh name="polySurface131_aiStandardSurface2_0" geometry={nodes.polySurface131_aiStandardSurface2_0.geometry} material={materials.aiStandardSurface2} />
                    </group>
                    <group name="polySurface132">
                      <mesh name="polySurface132_aiStandardSurface2_0" geometry={nodes.polySurface132_aiStandardSurface2_0.geometry} material={materials.aiStandardSurface2} />
                    </group>
                    <group name="polySurface133">
                      <mesh name="polySurface133_aiStandardSurface2_0" geometry={nodes.polySurface133_aiStandardSurface2_0.geometry} material={materials.aiStandardSurface2} />
                    </group>
                    <group name="polySurface134">
                      <mesh name="polySurface134_aiStandardSurface2_0" geometry={nodes.polySurface134_aiStandardSurface2_0.geometry} material={materials.aiStandardSurface2} />
                    </group>
                    <group name="polySurface135">
                      <mesh name="polySurface135_aiStandardSurface2_0" geometry={nodes.polySurface135_aiStandardSurface2_0.geometry} material={materials.aiStandardSurface2} />
                    </group>
                    <group name="polySurface136">
                      <mesh name="polySurface136_aiStandardSurface2_0" geometry={nodes.polySurface136_aiStandardSurface2_0.geometry} material={materials.aiStandardSurface2} />
                    </group>
                    <group name="polySurface137">
                      <mesh name="polySurface137_aiStandardSurface2_0" geometry={nodes.polySurface137_aiStandardSurface2_0.geometry} material={materials.aiStandardSurface2} />
                    </group>
                    <group name="polySurface138">
                      <mesh name="polySurface138_aiStandardSurface2_0" geometry={nodes.polySurface138_aiStandardSurface2_0.geometry} material={materials.aiStandardSurface2} />
                    </group>
                    <group name="polySurface139" position={[0, -0.087, 0]}>
                      <mesh name="polySurface139_aiStandardSurface2_0" geometry={nodes.polySurface139_aiStandardSurface2_0.geometry} material={materials.aiStandardSurface2} />
                    </group>
                    <group name="polySurface140" position={[0, -0.087, 0]}>
                      <mesh name="polySurface140_aiStandardSurface2_0" geometry={nodes.polySurface140_aiStandardSurface2_0.geometry} material={materials.aiStandardSurface2} />
                    </group>
                    <group name="polySurface141">
                      <mesh name="polySurface141_aiStandardSurface2_0" geometry={nodes.polySurface141_aiStandardSurface2_0.geometry} material={materials.aiStandardSurface2} />
                    </group>
                    <group name="polySurface142">
                      <mesh name="polySurface142_aiStandardSurface2_0" geometry={nodes.polySurface142_aiStandardSurface2_0.geometry} material={materials.aiStandardSurface2} />
                    </group>
                    <group name="polySurface143">
                      <mesh name="polySurface143_aiStandardSurface2_0" geometry={nodes.polySurface143_aiStandardSurface2_0.geometry} material={materials.aiStandardSurface2} />
                    </group>
                    <group name="polySurface144">
                      <mesh name="polySurface144_aiStandardSurface2_0" geometry={nodes.polySurface144_aiStandardSurface2_0.geometry} material={materials.aiStandardSurface2} />
                    </group>
                    <group name="polySurface145">
                      <mesh name="polySurface145_aiStandardSurface2_0" geometry={nodes.polySurface145_aiStandardSurface2_0.geometry} material={materials.aiStandardSurface2} />
                    </group>
                    <group name="polySurface146">
                      <mesh name="polySurface146_aiStandardSurface2_0" geometry={nodes.polySurface146_aiStandardSurface2_0.geometry} material={materials.aiStandardSurface2} />
                    </group>
                    <group name="polySurface147">
                      <mesh name="polySurface147_aiStandardSurface2_0" geometry={nodes.polySurface147_aiStandardSurface2_0.geometry} material={materials.aiStandardSurface2} />
                    </group>
                    <group name="polySurface148">
                      <mesh name="polySurface148_aiStandardSurface2_0" geometry={nodes.polySurface148_aiStandardSurface2_0.geometry} material={materials.aiStandardSurface2} />
                    </group>
                    <group name="polySurface149">
                      <mesh name="polySurface149_aiStandardSurface2_0" geometry={nodes.polySurface149_aiStandardSurface2_0.geometry} material={materials.aiStandardSurface2} />
                    </group>
                    <group name="polySurface150">
                      <mesh name="polySurface150_aiStandardSurface2_0" geometry={nodes.polySurface150_aiStandardSurface2_0.geometry} material={materials.aiStandardSurface2} />
                    </group>
                    <group name="polySurface151">
                      <mesh name="polySurface151_aiStandardSurface6_0" geometry={nodes.polySurface151_aiStandardSurface6_0.geometry} material={materials.aiStandardSurface6} />
                    </group>
                  </group>
                  <group name="polySurface51">
                    <mesh name="polySurface51_aiStandardSurface1_0" geometry={nodes.polySurface51_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
                  </group>
                </group>
                <group name="group29">
                  <group name="polySurface48">
                    <mesh name="polySurface48_aiStandardSurface7_0" geometry={nodes.polySurface48_aiStandardSurface7_0.geometry} material={materials.aiStandardSurface7} />
                  </group>
                  <group name="polySurface47">
                    <mesh name="polySurface47_aiStandardSurface7_0" geometry={nodes.polySurface47_aiStandardSurface7_0.geometry} material={materials.aiStandardSurface7} />
                  </group>
                  <group name="polySurface46">
                    <mesh name="polySurface46_aiStandardSurface7_0" geometry={nodes.polySurface46_aiStandardSurface7_0.geometry} material={materials.aiStandardSurface7} />
                  </group>
                  <group name="polySurface45">
                    <mesh name="polySurface45_aiStandardSurface7_0" geometry={nodes.polySurface45_aiStandardSurface7_0.geometry} material={materials.aiStandardSurface7} />
                  </group>
                  <group name="polySurface44">
                    <mesh name="polySurface44_aiStandardSurface7_0" geometry={nodes.polySurface44_aiStandardSurface7_0.geometry} material={materials.aiStandardSurface7} />
                  </group>
                  <group name="polySurface43">
                    <mesh name="polySurface43_aiStandardSurface7_0" geometry={nodes.polySurface43_aiStandardSurface7_0.geometry} material={materials.aiStandardSurface7} />
                  </group>
                  <group name="polySurface42">
                    <mesh name="polySurface42_aiStandardSurface7_0" geometry={nodes.polySurface42_aiStandardSurface7_0.geometry} material={materials.aiStandardSurface7} />
                  </group>
                  <group name="polySurface41">
                    <mesh name="polySurface41_aiStandardSurface7_0" geometry={nodes.polySurface41_aiStandardSurface7_0.geometry} material={materials.aiStandardSurface7} />
                  </group>
                  <group name="polySurface40">
                    <mesh name="polySurface40_aiStandardSurface7_0" geometry={nodes.polySurface40_aiStandardSurface7_0.geometry} material={materials.aiStandardSurface7} />
                  </group>
                  <group name="polySurface39">
                    <mesh name="polySurface39_aiStandardSurface7_0" geometry={nodes.polySurface39_aiStandardSurface7_0.geometry} material={materials.aiStandardSurface7} />
                  </group>
                  <group name="polySurface38">
                    <mesh name="polySurface38_aiStandardSurface7_0" geometry={nodes.polySurface38_aiStandardSurface7_0.geometry} material={materials.aiStandardSurface7} />
                  </group>
                  <group name="polySurface37">
                    <mesh name="polySurface37_aiStandardSurface7_0" geometry={nodes.polySurface37_aiStandardSurface7_0.geometry} material={materials.aiStandardSurface7} />
                  </group>
                  <group name="polySurface36">
                    <mesh name="polySurface36_aiStandardSurface7_0" geometry={nodes.polySurface36_aiStandardSurface7_0.geometry} material={materials.aiStandardSurface7} />
                  </group>
                  <group name="polySurface35">
                    <mesh name="polySurface35_aiStandardSurface7_0" geometry={nodes.polySurface35_aiStandardSurface7_0.geometry} material={materials.aiStandardSurface7} />
                  </group>
                  <group name="polySurface34">
                    <mesh name="polySurface34_aiStandardSurface7_0" geometry={nodes.polySurface34_aiStandardSurface7_0.geometry} material={materials.aiStandardSurface7} />
                  </group>
                  <group name="polySurface33">
                    <mesh name="polySurface33_aiStandardSurface7_0" geometry={nodes.polySurface33_aiStandardSurface7_0.geometry} material={materials.aiStandardSurface7} />
                  </group>
                  <group name="polySurface32">
                    <mesh name="polySurface32_aiStandardSurface7_0" geometry={nodes.polySurface32_aiStandardSurface7_0.geometry} material={materials.aiStandardSurface7} />
                  </group>
                  <group name="polySurface30">
                    <mesh name="polySurface30_aiStandardSurface7_0" geometry={nodes.polySurface30_aiStandardSurface7_0.geometry} material={materials.aiStandardSurface7} />
                  </group>
                  <group name="polySurface29">
                    <mesh name="polySurface29_aiStandardSurface7_0" geometry={nodes.polySurface29_aiStandardSurface7_0.geometry} material={materials.aiStandardSurface7} />
                  </group>
                  <group name="polySurface24">
                    <mesh name="polySurface24_aiStandardSurface7_0" geometry={nodes.polySurface24_aiStandardSurface7_0.geometry} material={materials.aiStandardSurface7} />
                  </group>
                  <group name="polySurface23">
                    <mesh name="polySurface23_aiStandardSurface7_0" geometry={nodes.polySurface23_aiStandardSurface7_0.geometry} material={materials.aiStandardSurface7} />
                  </group>
                  <group name="polySurface22">
                    <mesh name="polySurface22_aiStandardSurface7_0" geometry={nodes.polySurface22_aiStandardSurface7_0.geometry} material={materials.aiStandardSurface7} />
                  </group>
                  <group name="polySurface21">
                    <mesh name="polySurface21_aiStandardSurface7_0" geometry={nodes.polySurface21_aiStandardSurface7_0.geometry} material={materials.aiStandardSurface7} />
                  </group>
                  <group name="polySurface20">
                    <mesh name="polySurface20_aiStandardSurface7_0" geometry={nodes.polySurface20_aiStandardSurface7_0.geometry} material={materials.aiStandardSurface7} />
                  </group>
                  <group name="polySurface19">
                    <mesh name="polySurface19_aiStandardSurface7_0" geometry={nodes.polySurface19_aiStandardSurface7_0.geometry} material={materials.aiStandardSurface7} />
                  </group>
                  <group name="polySurface18">
                    <mesh name="polySurface18_aiStandardSurface7_0" geometry={nodes.polySurface18_aiStandardSurface7_0.geometry} material={materials.aiStandardSurface7} />
                  </group>
                  <group name="polySurface17">
                    <mesh name="polySurface17_aiStandardSurface7_0" geometry={nodes.polySurface17_aiStandardSurface7_0.geometry} material={materials.aiStandardSurface7} />
                  </group>
                  <group name="polySurface16">
                    <mesh name="polySurface16_aiStandardSurface7_0" geometry={nodes.polySurface16_aiStandardSurface7_0.geometry} material={materials.aiStandardSurface7} />
                  </group>
                  <group name="polySurface15">
                    <mesh name="polySurface15_aiStandardSurface7_0" geometry={nodes.polySurface15_aiStandardSurface7_0.geometry} material={materials.aiStandardSurface7} />
                  </group>
                  <group name="polySurface14">
                    <mesh name="polySurface14_aiStandardSurface7_0" geometry={nodes.polySurface14_aiStandardSurface7_0.geometry} material={materials.aiStandardSurface7} />
                  </group>
                  <group name="polySurface13">
                    <mesh name="polySurface13_aiStandardSurface7_0" geometry={nodes.polySurface13_aiStandardSurface7_0.geometry} material={materials.aiStandardSurface7} />
                  </group>
                  <group name="polySurface12">
                    <mesh name="polySurface12_aiStandardSurface7_0" geometry={nodes.polySurface12_aiStandardSurface7_0.geometry} material={materials.aiStandardSurface7} />
                  </group>
                  <group name="polySurface11">
                    <mesh name="polySurface11_aiStandardSurface7_0" geometry={nodes.polySurface11_aiStandardSurface7_0.geometry} material={materials.aiStandardSurface7} />
                  </group>
                  <group name="polySurface10">
                    <mesh name="polySurface10_aiStandardSurface7_0" geometry={nodes.polySurface10_aiStandardSurface7_0.geometry} material={materials.aiStandardSurface7} />
                  </group>
                  <group name="polySurface7">
                    <mesh name="polySurface7_aiStandardSurface7_0" geometry={nodes.polySurface7_aiStandardSurface7_0.geometry} material={materials.aiStandardSurface7} />
                  </group>
                  <group name="polySurface54">
                    <mesh name="polySurface54_aiStandardSurface7_0" geometry={nodes.polySurface54_aiStandardSurface7_0.geometry} material={materials.aiStandardSurface7} />
                  </group>
                  <group name="polySurface55">
                    <mesh name="polySurface55_aiStandardSurface7_0" geometry={nodes.polySurface55_aiStandardSurface7_0.geometry} material={materials.aiStandardSurface7} />
                  </group>
                  <group name="polySurface56">
                    <mesh name="polySurface56_aiStandardSurface7_0" geometry={nodes.polySurface56_aiStandardSurface7_0.geometry} material={materials.aiStandardSurface7} />
                  </group>
                  <group name="polySurface57">
                    <mesh name="polySurface57_aiStandardSurface7_0" geometry={nodes.polySurface57_aiStandardSurface7_0.geometry} material={materials.aiStandardSurface7} />
                  </group>
                  <group name="polySurface58">
                    <mesh name="polySurface58_aiStandardSurface7_0" geometry={nodes.polySurface58_aiStandardSurface7_0.geometry} material={materials.aiStandardSurface7} />
                  </group>
                  <group name="polySurface59">
                    <mesh name="polySurface59_aiStandardSurface7_0" geometry={nodes.polySurface59_aiStandardSurface7_0.geometry} material={materials.aiStandardSurface7} />
                  </group>
                  <group name="polySurface60">
                    <mesh name="polySurface60_aiStandardSurface7_0" geometry={nodes.polySurface60_aiStandardSurface7_0.geometry} material={materials.aiStandardSurface7} />
                  </group>
                  <group name="polySurface61">
                    <mesh name="polySurface61_aiStandardSurface7_0" geometry={nodes.polySurface61_aiStandardSurface7_0.geometry} material={materials.aiStandardSurface7} />
                  </group>
                  <group name="polySurface62">
                    <mesh name="polySurface62_aiStandardSurface7_0" geometry={nodes.polySurface62_aiStandardSurface7_0.geometry} material={materials.aiStandardSurface7} />
                  </group>
                  <group name="polySurface63">
                    <mesh name="polySurface63_aiStandardSurface7_0" geometry={nodes.polySurface63_aiStandardSurface7_0.geometry} material={materials.aiStandardSurface7} />
                  </group>
                  <group name="polySurface64">
                    <mesh name="polySurface64_aiStandardSurface7_0" geometry={nodes.polySurface64_aiStandardSurface7_0.geometry} material={materials.aiStandardSurface7} />
                  </group>
                  <group name="polySurface65">
                    <mesh name="polySurface65_aiStandardSurface7_0" geometry={nodes.polySurface65_aiStandardSurface7_0.geometry} material={materials.aiStandardSurface7} />
                  </group>
                  <group name="polySurface66">
                    <mesh name="polySurface66_aiStandardSurface7_0" geometry={nodes.polySurface66_aiStandardSurface7_0.geometry} material={materials.aiStandardSurface7} />
                  </group>
                  <group name="polySurface67">
                    <mesh name="polySurface67_aiStandardSurface7_0" geometry={nodes.polySurface67_aiStandardSurface7_0.geometry} material={materials.aiStandardSurface7} />
                  </group>
                  <group name="polySurface68">
                    <mesh name="polySurface68_aiStandardSurface7_0" geometry={nodes.polySurface68_aiStandardSurface7_0.geometry} material={materials.aiStandardSurface7} />
                  </group>
                  <group name="polySurface69">
                    <mesh name="polySurface69_aiStandardSurface7_0" geometry={nodes.polySurface69_aiStandardSurface7_0.geometry} material={materials.aiStandardSurface7} />
                  </group>
                  <group name="polySurface70">
                    <mesh name="polySurface70_aiStandardSurface7_0" geometry={nodes.polySurface70_aiStandardSurface7_0.geometry} material={materials.aiStandardSurface7} />
                  </group>
                  <group name="polySurface71">
                    <mesh name="polySurface71_aiStandardSurface7_0" geometry={nodes.polySurface71_aiStandardSurface7_0.geometry} material={materials.aiStandardSurface7} />
                  </group>
                  <group name="polySurface72">
                    <mesh name="polySurface72_aiStandardSurface7_0" geometry={nodes.polySurface72_aiStandardSurface7_0.geometry} material={materials.aiStandardSurface7} />
                  </group>
                  <group name="polySurface73">
                    <mesh name="polySurface73_aiStandardSurface7_0" geometry={nodes.polySurface73_aiStandardSurface7_0.geometry} material={materials.aiStandardSurface7} />
                  </group>
                  <group name="polySurface74">
                    <mesh name="polySurface74_aiStandardSurface7_0" geometry={nodes.polySurface74_aiStandardSurface7_0.geometry} material={materials.aiStandardSurface7} />
                  </group>
                  <group name="polySurface75" position={[0, -0.086, 0]}>
                    <mesh name="polySurface75_aiStandardSurface7_0" geometry={nodes.polySurface75_aiStandardSurface7_0.geometry} material={materials.aiStandardSurface7} />
                  </group>
                  <group name="polySurface76" position={[0, -0.086, 0]}>
                    <mesh name="polySurface76_aiStandardSurface7_0" geometry={nodes.polySurface76_aiStandardSurface7_0.geometry} material={materials.aiStandardSurface7} />
                  </group>
                  <group name="polySurface77">
                    <mesh name="polySurface77_aiStandardSurface7_0" geometry={nodes.polySurface77_aiStandardSurface7_0.geometry} material={materials.aiStandardSurface7} />
                  </group>
                  <group name="polySurface78">
                    <mesh name="polySurface78_aiStandardSurface7_0" geometry={nodes.polySurface78_aiStandardSurface7_0.geometry} material={materials.aiStandardSurface7} />
                  </group>
                  <group name="polySurface79">
                    <mesh name="polySurface79_aiStandardSurface7_0" geometry={nodes.polySurface79_aiStandardSurface7_0.geometry} material={materials.aiStandardSurface7} />
                  </group>
                  <group name="polySurface80">
                    <mesh name="polySurface80_aiStandardSurface7_0" geometry={nodes.polySurface80_aiStandardSurface7_0.geometry} material={materials.aiStandardSurface7} />
                  </group>
                  <group name="polySurface81">
                    <mesh name="polySurface81_aiStandardSurface7_0" geometry={nodes.polySurface81_aiStandardSurface7_0.geometry} material={materials.aiStandardSurface7} />
                  </group>
                  <group name="polySurface82">
                    <mesh name="polySurface82_aiStandardSurface7_0" geometry={nodes.polySurface82_aiStandardSurface7_0.geometry} material={materials.aiStandardSurface7} />
                  </group>
                  <group name="polySurface83">
                    <mesh name="polySurface83_aiStandardSurface7_0" geometry={nodes.polySurface83_aiStandardSurface7_0.geometry} material={materials.aiStandardSurface7} />
                  </group>
                  <group name="polySurface84">
                    <mesh name="polySurface84_aiStandardSurface7_0" geometry={nodes.polySurface84_aiStandardSurface7_0.geometry} material={materials.aiStandardSurface7} />
                  </group>
                  <group name="polySurface85">
                    <mesh name="polySurface85_aiStandardSurface7_0" geometry={nodes.polySurface85_aiStandardSurface7_0.geometry} material={materials.aiStandardSurface7} />
                  </group>
                  <group name="polySurface86">
                    <mesh name="polySurface86_aiStandardSurface7_0" geometry={nodes.polySurface86_aiStandardSurface7_0.geometry} material={materials.aiStandardSurface7} />
                  </group>
                  <group name="polySurface87">
                    <mesh name="polySurface87_aiStandardSurface7_0" geometry={nodes.polySurface87_aiStandardSurface7_0.geometry} material={materials.aiStandardSurface7} />
                  </group>
                  <group name="group22">
                    <group name="group27">
                      <group name="polySurface89">
                        <mesh name="polySurface89_aiStandardSurface7_0" geometry={nodes.polySurface89_aiStandardSurface7_0.geometry} material={materials.aiStandardSurface7} />
                      </group>
                      <group name="polySurface90">
                        <mesh name="polySurface90_aiStandardSurface7_0" geometry={nodes.polySurface90_aiStandardSurface7_0.geometry} material={materials.aiStandardSurface7} />
                      </group>
                      <group name="polySurface91">
                        <mesh name="polySurface91_aiStandardSurface7_0" geometry={nodes.polySurface91_aiStandardSurface7_0.geometry} material={materials.aiStandardSurface7} />
                      </group>
                      <group name="polySurface92">
                        <mesh name="polySurface92_aiStandardSurface7_0" geometry={nodes.polySurface92_aiStandardSurface7_0.geometry} material={materials.aiStandardSurface7} />
                      </group>
                      <group name="polySurface93">
                        <mesh name="polySurface93_aiStandardSurface7_0" geometry={nodes.polySurface93_aiStandardSurface7_0.geometry} material={materials.aiStandardSurface7} />
                      </group>
                      <group name="polySurface94">
                        <mesh name="polySurface94_aiStandardSurface7_0" geometry={nodes.polySurface94_aiStandardSurface7_0.geometry} material={materials.aiStandardSurface7} />
                      </group>
                      <group name="polySurface95">
                        <mesh name="polySurface95_aiStandardSurface7_0" geometry={nodes.polySurface95_aiStandardSurface7_0.geometry} material={materials.aiStandardSurface7} />
                      </group>
                      <group name="polySurface96">
                        <mesh name="polySurface96_aiStandardSurface7_0" geometry={nodes.polySurface96_aiStandardSurface7_0.geometry} material={materials.aiStandardSurface7} />
                      </group>
                      <group name="polySurface97">
                        <mesh name="polySurface97_aiStandardSurface7_0" geometry={nodes.polySurface97_aiStandardSurface7_0.geometry} material={materials.aiStandardSurface7} />
                      </group>
                      <group name="polySurface102">
                        <mesh name="polySurface102_aiStandardSurface7_0" geometry={nodes.polySurface102_aiStandardSurface7_0.geometry} material={materials.aiStandardSurface7} />
                      </group>
                      <group name="polySurface103">
                        <mesh name="polySurface103_aiStandardSurface7_0" geometry={nodes.polySurface103_aiStandardSurface7_0.geometry} material={materials.aiStandardSurface7} />
                      </group>
                      <group name="polySurface104">
                        <mesh name="polySurface104_aiStandardSurface7_0" geometry={nodes.polySurface104_aiStandardSurface7_0.geometry} material={materials.aiStandardSurface7} />
                      </group>
                      <group name="polySurface105">
                        <mesh name="polySurface105_aiStandardSurface7_0" geometry={nodes.polySurface105_aiStandardSurface7_0.geometry} material={materials.aiStandardSurface7} />
                      </group>
                      <group name="polySurface106">
                        <mesh name="polySurface106_aiStandardSurface7_0" geometry={nodes.polySurface106_aiStandardSurface7_0.geometry} material={materials.aiStandardSurface7} />
                      </group>
                      <group name="polySurface107">
                        <mesh name="polySurface107_aiStandardSurface7_0" geometry={nodes.polySurface107_aiStandardSurface7_0.geometry} material={materials.aiStandardSurface7} />
                      </group>
                      <group name="polySurface108">
                        <mesh name="polySurface108_aiStandardSurface7_0" geometry={nodes.polySurface108_aiStandardSurface7_0.geometry} material={materials.aiStandardSurface7} />
                      </group>
                      <group name="polySurface109">
                        <mesh name="polySurface109_aiStandardSurface7_0" geometry={nodes.polySurface109_aiStandardSurface7_0.geometry} material={materials.aiStandardSurface7} />
                      </group>
                      <group name="polySurface110">
                        <mesh name="polySurface110_aiStandardSurface7_0" geometry={nodes.polySurface110_aiStandardSurface7_0.geometry} material={materials.aiStandardSurface7} />
                      </group>
                      <group name="polySurface111">
                        <mesh name="polySurface111_aiStandardSurface7_0" geometry={nodes.polySurface111_aiStandardSurface7_0.geometry} material={materials.aiStandardSurface7} />
                      </group>
                      <group name="polySurface112">
                        <mesh name="polySurface112_aiStandardSurface7_0" geometry={nodes.polySurface112_aiStandardSurface7_0.geometry} material={materials.aiStandardSurface7} />
                      </group>
                      <group name="polySurface113">
                        <mesh name="polySurface113_aiStandardSurface7_0" geometry={nodes.polySurface113_aiStandardSurface7_0.geometry} material={materials.aiStandardSurface7} />
                      </group>
                      <group name="polySurface114">
                        <mesh name="polySurface114_aiStandardSurface7_0" geometry={nodes.polySurface114_aiStandardSurface7_0.geometry} material={materials.aiStandardSurface7} />
                      </group>
                      <group name="polySurface115">
                        <mesh name="polySurface115_aiStandardSurface7_0" geometry={nodes.polySurface115_aiStandardSurface7_0.geometry} material={materials.aiStandardSurface7} />
                      </group>
                      <group name="polySurface116">
                        <mesh name="polySurface116_aiStandardSurface7_0" geometry={nodes.polySurface116_aiStandardSurface7_0.geometry} material={materials.aiStandardSurface7} />
                      </group>
                    </group>
                  </group>
                </group>
                <group name="polySurface117group28">
                  <group name="polySurface152">
                    <mesh name="polySurface152_aiStandardSurface8_0" geometry={nodes.polySurface152_aiStandardSurface8_0.geometry} material={materials.aiStandardSurface8} />
                  </group>
                  <group name="polySurface153">
                    <mesh name="polySurface153_aiStandardSurface8_0" geometry={nodes.polySurface153_aiStandardSurface8_0.geometry} material={materials.aiStandardSurface8} />
                  </group>
                  <group name="polySurface154">
                    <mesh name="polySurface154_aiStandardSurface8_0" geometry={nodes.polySurface154_aiStandardSurface8_0.geometry} material={materials.aiStandardSurface8} />
                  </group>
                  <group name="polySurface155">
                    <mesh name="polySurface155_aiStandardSurface8_0" geometry={nodes.polySurface155_aiStandardSurface8_0.geometry} material={materials.aiStandardSurface8} />
                  </group>
                  <group name="polySurface156">
                    <mesh name="polySurface156_aiStandardSurface8_0" geometry={nodes.polySurface156_aiStandardSurface8_0.geometry} material={materials.aiStandardSurface8} />
                  </group>
                  <group name="polySurface157">
                    <mesh name="polySurface157_aiStandardSurface8_0" geometry={nodes.polySurface157_aiStandardSurface8_0.geometry} material={materials.aiStandardSurface8} />
                  </group>
                  <group name="polySurface158">
                    <mesh name="polySurface158_aiStandardSurface8_0" geometry={nodes.polySurface158_aiStandardSurface8_0.geometry} material={materials.aiStandardSurface8} />
                  </group>
                  <group name="polySurface162">
                    <group name="transform24" />
                  </group>
                  <group name="polySurface163_1">
                    <group name="transform25" />
                  </group>
                  <group name="polySurface164">
                    <group name="transform23" />
                  </group>
                  <group name="polySurface167">
                    <mesh name="polySurface167_aiStandardSurface8_0" geometry={nodes.polySurface167_aiStandardSurface8_0.geometry} material={materials.aiStandardSurface8} />
                  </group>
                  <group name="transform1" />
                </group>
                <group name="pCube52group22group24group25">
                  <group name="transform5" />
                </group>
                <group name="group22group24group25pumpkin_low">
                  <group name="transform20" />
                </group>
                <group name="group22group24group25pPlane14">
                  <group name="transform19" />
                </group>
                <group name="group24group25Mushroom_02_Base3group19">
                  <group name="transform14" />
                </group>
                <group name="group24group25group19Mushroom_02_Base4">
                  <group name="transform15" />
                </group>
                <group name="group22group24group25pumpkin_low1">
                  <group name="transform16" />
                </group>
                <group name="group22group24group25pumpkinhead_low">
                  <group name="transform12" />
                </group>
                <group name="group22group24group25pCube65">
                  <group name="transform13" />
                </group>
                <group name="group22group24group25pCube63">
                  <group name="transform17" />
                </group>
                <group name="group22group24group25pCube64">
                  <group name="transform18" />
                </group>
                <group name="group22group24group25pCube53">
                  <group name="transform10" />
                </group>
                <group name="group22group24group25pCube54">
                  <group name="transform11" />
                </group>
                <group name="group22group24group25pCylinder7">
                  <group name="transform3" />
                </group>
                <group name="group22group24group25pCube17">
                  <group name="transform4" />
                </group>
                <group name="group22group24group25pCylinder8">
                  <group name="transform2" />
                </group>
                <group name="group24group25group19Mushroom_02_Base2">
                  <group name="transform9" />
                </group>
                <group name="group24group25group19Mushroom_02_Base">
                  <group name="transform6" />
                </group>
                <group name="group22group24group25pCylinder1">
                  <group name="transform7" />
                </group>
                <group name="group22group24group25pCylinder2">
                  <group name="transform8" />
                </group>
                <group name="group22group24group25pumpkin_low2">
                  <group name="polySurface168">
                    <mesh name="polySurface168_aiStandardSurface9_0" geometry={nodes.polySurface168_aiStandardSurface9_0.geometry} material={materials.aiStandardSurface9} />
                  </group>
                  <group name="polySurface169">
                    <mesh name="polySurface169_aiStandardSurface9_0" geometry={nodes.polySurface169_aiStandardSurface9_0.geometry} material={materials.aiStandardSurface9} />
                  </group>
                  <group name="polySurface172">
                    <group name="polySurface186">
                      <mesh name="polySurface186_aiStandardSurface7_0" geometry={nodes.polySurface186_aiStandardSurface7_0.geometry} material={materials.aiStandardSurface7} />
                    </group>
                    <group name="polySurface187">
                      <mesh name="polySurface187_aiStandardSurface9_0" geometry={nodes.polySurface187_aiStandardSurface9_0.geometry} material={materials.aiStandardSurface9} />
                    </group>
                    <group name="transform22" />
                  </group>
                  <group name="polySurface173">
                    <mesh name="polySurface173_aiStandardSurface9_0" geometry={nodes.polySurface173_aiStandardSurface9_0.geometry} material={materials.aiStandardSurface9} />
                  </group>
                  <group name="polySurface174">
                    <mesh name="polySurface174_aiStandardSurface9_0" geometry={nodes.polySurface174_aiStandardSurface9_0.geometry} material={materials.aiStandardSurface9} />
                  </group>
                  <group name="polySurface175">
                    <mesh name="polySurface175_aiStandardSurface9_0" geometry={nodes.polySurface175_aiStandardSurface9_0.geometry} material={materials.aiStandardSurface9} />
                  </group>
                  <group name="polySurface176">
                    <mesh name="polySurface176_aiStandardSurface9_0" geometry={nodes.polySurface176_aiStandardSurface9_0.geometry} material={materials.aiStandardSurface9} />
                  </group>
                  <group name="polySurface178">
                    <mesh name="polySurface178_aiStandardSurface9_0" geometry={nodes.polySurface178_aiStandardSurface9_0.geometry} material={materials.aiStandardSurface9} />
                  </group>
                  <group name="polySurface179">
                    <mesh name="polySurface179_aiStandardSurface9_0" geometry={nodes.polySurface179_aiStandardSurface9_0.geometry} material={materials.aiStandardSurface9} />
                  </group>
                  <group name="polySurface180">
                    <mesh name="polySurface180_aiStandardSurface9_0" geometry={nodes.polySurface180_aiStandardSurface9_0.geometry} material={materials.aiStandardSurface9} />
                  </group>
                  <group name="polySurface181">
                    <mesh name="polySurface181_aiStandardSurface9_0" geometry={nodes.polySurface181_aiStandardSurface9_0.geometry} material={materials.aiStandardSurface9} />
                  </group>
                  <group name="polySurface182">
                    <mesh name="polySurface182_aiStandardSurface9_0" geometry={nodes.polySurface182_aiStandardSurface9_0.geometry} material={materials.aiStandardSurface9} />
                  </group>
                  <group name="polySurface183">
                    <mesh name="polySurface183_aiStandardSurface9_0" geometry={nodes.polySurface183_aiStandardSurface9_0.geometry} material={materials.aiStandardSurface9} />
                  </group>
                  <group name="polySurface184">
                    <mesh name="polySurface184_aiStandardSurface9_0" geometry={nodes.polySurface184_aiStandardSurface9_0.geometry} material={materials.aiStandardSurface9} />
                  </group>
                  <group name="polySurface185">
                    <mesh name="polySurface185_aiStandardSurface9_0" geometry={nodes.polySurface185_aiStandardSurface9_0.geometry} material={materials.aiStandardSurface9} />
                  </group>
                  <group name="transform21" />
                </group>
                <group name="polySurface163">
                  <group name="polySurface188">
                    <mesh name="polySurface188_aiStandardSurface7_0" geometry={nodes.polySurface188_aiStandardSurface7_0.geometry} material={materials.aiStandardSurface7} />
                  </group>
                  <group name="polySurface189">
                    <mesh name="polySurface189_aiStandardSurface7_0" geometry={nodes.polySurface189_aiStandardSurface7_0.geometry} material={materials.aiStandardSurface7} />
                  </group>
                  <group name="polySurface190">
                    <mesh name="polySurface190_aiStandardSurface7_0" geometry={nodes.polySurface190_aiStandardSurface7_0.geometry} material={materials.aiStandardSurface7} />
                  </group>
                  <group name="polySurface191">
                    <mesh name="polySurface191_aiStandardSurface8_0" geometry={nodes.polySurface191_aiStandardSurface8_0.geometry} material={materials.aiStandardSurface8} />
                  </group>
                  <group name="transform26" />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('./models/halloween.glb')
